In [12]:
import numpy as np
from numpy import genfromtxt   # txt uzantılı dosyaları okumak için kullanılan method

## Reading in the Data Set

https://archive.ics.uci.edu/ml/datasets/banknote+authentication

In [13]:
data = genfromtxt('../DATA/bank_note_data.txt', delimiter=',')

In [14]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [15]:
labels = data[:,4]

In [16]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [17]:
features = data[:,0:4]

In [18]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [19]:
X = features
y = labels

## Split the Data into Training and Test

Its time to split the data into a train/test set. Keep in mind, sometimes people like to split 3 ways, train/test/validation. We'll keep things simple for now. **Remember to check out the video explanation as to why we split and what all the parameters mean!**

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [22]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [23]:
X_test

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.5127  ,  2.9073  ,  1.0579  ,  0.40774 ],
       [ 5.504   , 10.3671  , -4.413   , -4.0211  ],
       [-0.2062  ,  9.2207  , -3.7044  , -6.8103  ]])

In [24]:
len(X_train)

919

In [25]:
len(X_test)

453

In [26]:
y_train

array([1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1.,
       1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1.,
       0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0.,
       1., 0., 0., 1., 0.

In [27]:
len(y_train)

919

## Standardizing the Data

Usually when using Neural Networks, you will get better performance when you standardize the data. Standardization just means normalizing the values to all fit between a certain range, like 0-1, or -1 to 1.

The scikit learn library also provides a nice function for this.

http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html

In [28]:
from sklearn.preprocessing import MinMaxScaler

In [29]:
scaler = MinMaxScaler()

In [30]:
scaler.fit(X_train)

MinMaxScaler()

In [31]:
scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

In [32]:
X_train.max()

17.9274

In [33]:
scaled_X_train.max()

1.0000000000000002

In [34]:
scaled_X_train.min()

0.0

## Building the Network with Keras

Let's build a simple neural network!

In [35]:
import tensorflow as tf

In [36]:
from keras.models import Sequential
from keras.layers import Dense

In [37]:
model = Sequential()

model.add(Dense(4,input_dim =4,activation='relu'))

model.add(Dense(8, activation='relu'))

model.add(Dense(1,activation='sigmoid'))

In [38]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [39]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
29/29 - 2s - loss: 0.7147 - accuracy: 0.4570 - 2s/epoch - 63ms/step
Epoch 2/50
29/29 - 0s - loss: 0.7043 - accuracy: 0.4505 - 112ms/epoch - 4ms/step
Epoch 3/50
29/29 - 0s - loss: 0.6970 - accuracy: 0.4494 - 102ms/epoch - 4ms/step
Epoch 4/50
29/29 - 0s - loss: 0.6922 - accuracy: 0.5419 - 101ms/epoch - 3ms/step
Epoch 5/50
29/29 - 0s - loss: 0.6894 - accuracy: 0.5495 - 102ms/epoch - 4ms/step
Epoch 6/50
29/29 - 0s - loss: 0.6864 - accuracy: 0.5495 - 117ms/epoch - 4ms/step
Epoch 7/50
29/29 - 0s - loss: 0.6825 - accuracy: 0.5495 - 112ms/epoch - 4ms/step
Epoch 8/50
29/29 - 0s - loss: 0.6770 - accuracy: 0.5495 - 97ms/epoch - 3ms/step
Epoch 9/50
29/29 - 0s - loss: 0.6698 - accuracy: 0.5495 - 90ms/epoch - 3ms/step
Epoch 10/50
29/29 - 0s - loss: 0.6613 - accuracy: 0.5495 - 90ms/epoch - 3ms/step
Epoch 11/50
29/29 - 0s - loss: 0.6519 - accuracy: 0.5495 - 89ms/epoch - 3ms/step
Epoch 12/50
29/29 - 0s - loss: 0.6411 - accuracy: 0.5495 - 98ms/epoch - 3ms/step
Epoch 13/50
29/29 - 0s - loss: 0

## Predicting New Unseen Data

Let's see how we did by predicting on **new data**. Remember, our model has **never** seen the test data that we scaled previously! This process is the exact same process you would use on totally brand new data. For example , a brand new bank note that you just analyzed .

In [40]:
scaled_X_test

array([[0.62098955, 0.75284662, 0.21900753, 0.5730998 ],
       [0.48778602, 0.82175665, 0.09174727, 0.56211079],
       [0.51158363, 0.77924916, 0.13830875, 0.50392598],
       ...,
       [0.76115065, 0.62415668, 0.27251204, 0.83616757],
       [0.9047516 , 0.90329171, 0.03658247, 0.42267079],
       [0.49296526, 0.86039507, 0.06714046, 0.1622583 ]])

In [41]:
model.predict(scaled_X_test)

15/15 [==============================] - 0s 2ms/step


array([[5.11616692e-02],
       [3.89393508e-01],
       [2.33346894e-01],
       [5.58120720e-02],
       [4.81757745e-02],
       [2.77441777e-02],
       [1.73661411e-01],
       [1.31419236e-02],
       [4.73432057e-02],
       [1.22208923e-01],
       [5.01304626e-01],
       [8.41059983e-01],
       [1.53265327e-01],
       [7.81496167e-01],
       [5.33360958e-01],
       [2.54242897e-01],
       [8.91329944e-01],
       [9.00647581e-01],
       [8.39804590e-01],
       [8.10824692e-01],
       [2.56861039e-02],
       [8.21274444e-02],
       [8.39393139e-01],
       [1.98665112e-02],
       [9.52813685e-01],
       [2.52506454e-02],
       [1.32929487e-02],
       [8.37087691e-01],
       [7.64940924e-04],
       [3.58464313e-03],
       [6.88997984e-01],
       [1.04774982e-01],
       [1.59771338e-01],
       [9.22621548e-01],
       [9.42549527e-01],
       [1.07848216e-02],
       [4.72641826e-01],
       [7.75087595e-01],
       [8.58721673e-01],
       [8.99686292e-02],


In [42]:
pred = (model.predict(scaled_X_test) > 0.5).astype("int32")

15/15 [==============================] - 0s 2ms/step


In [43]:
pred

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    

# Evaluating Model Performance

So how well did we do? How do we actually measure "well". Is 95% accuracy good enough? It all depends on the situation. Also we need to take into account things like recall and precision. Make sure to watch the video discussion on classification evaluation before running this code!

In [44]:
model.metrics_names

['loss', 'accuracy']

In [45]:
model.evaluate(x=scaled_X_test,y=y_test)

15/15 [==============================] - 0s 3ms/step - loss: 0.1748 - accuracy: 0.9514


[0.1748455911874771, 0.951434850692749]

In [46]:
from sklearn.metrics import confusion_matrix,classification_report

In [47]:
predictions = (model.predict(scaled_X_test) > 0.5).astype("int32")

15/15 [==============================] - 0s 2ms/step


In [48]:
confusion_matrix(y_test,predictions)

array([[254,   3],
       [ 19, 177]], dtype=int64)

In [49]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         0.0       0.93      0.99      0.96       257
         1.0       0.98      0.90      0.94       196

    accuracy                           0.95       453
   macro avg       0.96      0.95      0.95       453
weighted avg       0.95      0.95      0.95       453



## Saving and Loading Models

Now that we have a model trained, let's see how we can save and load it.

In [50]:
model.save('myfirstmodel.h5')

In [51]:
from keras.models import load_model

In [52]:
newmodel = load_model('myfirstmodel.h5')

In [53]:
pred = (newmodel.predict(X_test) > 0.5).astype("int32")

15/15 [==============================] - 0s 2ms/step


In [54]:
pred

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
    